#!/bin/bash

# Ustawienie zmiennych środowiskowych
export PROJECT_ID=$(gcloud config get-value project)
export REGION="europe-west1"
export EMBEDDING_SERVICE="embedding-gemma"
export LLM_SERVICE="bielik"
export BIGQUERY_DATASET="rag_dataset"
export BIGQUERY_TABLE="hotel_rules"
export BUCKET_NAME_SOURCE="warsztat-eskadra-bielika-modele"
export BUCKET_NAME_LLM="$PROJECT_ID-eskadra-bielik-llm"
export BUCKET_NAME_EMBEDDING="$PROJECT_ID-eskadra-bielik-embedding"
export OLLAMA_REPO_NAME="ollama-repo"
export OLLAMA_REPO_DESCRIPTION="Ollama obraz do uruchomienia modeli LLM->Bielik i EMBEDDING->Gemma"
# Konfiguracja Pub/Sub — temat w projekcie organizatora warsztatu
export PUBSUB_TOPIC_NAME="nadaj-mi-dostep-do-cloud-storage"
export PUBSUB_PROJECT_ID="bielik-greg-cloud-ai-ttt-pl"
export PUBSUB_PUBLISH_TOPIC="projects/$PUBSUB_PROJECT_ID/topics/$PUBSUB_TOPIC_NAME"

echo ""
echo "======================================================"
echo " Zmienne środowiskowe wczytane pomyślnie!"
echo " [!] Materiał warsztatowy — tylko do celów edukacyjnych."
echo "======================================================"
echo ""
printf "  %-10s\n" "Projekt / region:"
printf "    %-25s = %s\n" "PROJECT_ID"    "$PROJECT_ID"
printf "    %-25s = %s\n" "REGION"        "$REGION"
echo ""
printf "  %-10s\n" "Modele (Cloud Run):"
printf "    %-25s = %s\n" "LLM_SERVICE"       "$LLM_SERVICE"
printf "    %-25s = %s\n" "EMBEDDING_SERVICE" "$EMBEDDING_SERVICE"
echo ""
printf "  %-10s\n" "BigQuery:"
printf "    %-25s = %s\n" "BIGQUERY_DATASET" "$BIGQUERY_DATASET"
printf "    %-25s = %s\n" "BIGQUERY_TABLE"   "$BIGQUERY_TABLE"
echo ""
printf "  %-10s\n" "Cloud Storage:"
printf "    %-25s = %s\n" "BUCKET_NAME_SOURCE"    "$BUCKET_NAME_SOURCE"
printf "    %-25s = %s\n" "BUCKET_NAME_LLM"       "$BUCKET_NAME_LLM"
printf "    %-25s = %s\n" "BUCKET_NAME_EMBEDDING" "$BUCKET_NAME_EMBEDDING"
echo ""
printf "  %-10s\n" "Artifact Registry:"
printf "    %-25s = %s\n" "OLLAMA_REPO_NAME" "$OLLAMA_REPO_NAME"
echo ""
printf "  %-10s\n" "Pub/Sub:"
printf "    %-25s = %s\n" "PUBSUB_PUBLISH_TOPIC" "$PUBSUB_PUBLISH_TOPIC"
echo ""
echo "======================================================"
echo " Nowy terminal? Uruchom ponownie: source setup_env.sh"
echo "======================================================"
echo ""
