#!/bin/bash

# Ustawienie zmiennych środowiskowych
export PROJECT_ID=$(gcloud config get-value project)
export REGION="europe-west1"
export EMBEDDING_SERVICE="embedding-gemma"
export LLM_SERVICE="bielik"
export BIGQUERY_DATASET="rag_dataset"
export BIGQUERY_TABLE="hotel_rules"
export BUCKET_NAME_SOURCE="warsztat-eskadra-bielika-modele"
export BUCKET_NAME_LLM="$PROJECT_ID-eskadra-bielik-llm"
export BUCKET_NAME_EMBEDDING="$PROJECT_ID-eskadra-bielik-embedding"
export OLLAMA_REPO_NAME="ollama-repo"
export OLLAMA_REPO_DESCRIPTION="Ollama obraz do uruchomienia modeli LLM->Bielik i EMBEDDING->Gemma"
# Konfiguracja Pub/Sub — temat w projekcie organizatora warsztatu
export PUBSUB_TOPIC_NAME="nadaj-mi-dostep-do-cloud-storage"
export PUBSUB_PROJECT_ID="bielik-greg-cloud-ai-ttt-pl"
export PUBSUB_PUBLISH_TOPIC="projects/$PUBSUB_PROJECT_ID/topics/$PUBSUB_TOPIC_NAME"

echo ""
echo "======================================================"
echo " UWAGA: Materiał warsztatowy - tylko do celów edukacyjnych!"
echo " Nie stosować w środowiskach produkcyjnych."
echo "======================================================"
echo ""
echo "======================================================"
echo " Zmienne środowiskowe wczytane pomyślnie!"
echo "======================================================"
echo ""
echo "  PROJECT_ID=$PROJECT_ID"
echo "    -> ID Twojego projektu Google Cloud."
echo "    -> Używane w: krokach 2, 3, 4, 5 (wszystkie usługi GCP)"
echo ""
echo "  REGION=$REGION"
echo "    -> Region Google Cloud, w którym uruchamiane są usługi."
echo "    -> Używane w: krokach 3, 5 (Cloud Run)"
echo ""
echo "  LLM_SERVICE=$LLM_SERVICE"
echo "    -> Nazwa usługi Cloud Run z modelem językowym Bielik."
echo "    -> Używane w: kroku 3 (deploy modelu LLM)"
echo ""
echo "  EMBEDDING_SERVICE=$EMBEDDING_SERVICE"
echo "    -> Nazwa usługi Cloud Run z modelem embeddingowym EmbeddingGemma."
echo "    -> Używane w: kroku 3 (deploy modelu embeddingowego)"
echo ""
echo "  BIGQUERY_DATASET=$BIGQUERY_DATASET"
echo "    -> Nazwa zbioru danych (dataset) w BigQuery."
echo "    -> Używane w: kroku 4 (inicjalizacja bazy) i kroku 6 (wyszukiwanie RAG)"
echo ""
echo "  BIGQUERY_TABLE=$BIGQUERY_TABLE"
echo "    -> Nazwa tabeli w BigQuery przechowującej dokumenty i wektory."
echo "    -> Używane w: kroku 4 (inicjalizacja bazy) i kroku 6 (wyszukiwanie RAG)"
echo ""
echo "  BUCKET_NAME_SOURCE=$BUCKET_NAME_SOURCE"
echo "    -> Nazwa publicznego bucketu z modelami źródłowymi."
echo "    -> Używane w: kroku 3 (kopiowanie modeli)"
echo ""
echo "  BUCKET_NAME_LLM=$BUCKET_NAME_LLM"
echo "    -> Nazwa prywatnego bucketu dla modelu LLM w Twoim projekcie."
echo "    -> Używane w: kroku 3 (deploy modelu LLM)"
echo ""
echo "  BUCKET_NAME_EMBEDDING=$BUCKET_NAME_EMBEDDING"
echo "    -> Nazwa prywatnego bucketu dla modelu embeddingowego w Twoim projekcie."
echo "    -> Używane w: kroku 3 (deploy modelu embeddingowego)"
echo ""
echo "  OLLAMA_REPO_NAME=$OLLAMA_REPO_NAME"
echo "    -> Nazwa repozytorium na Artifact Registry."
echo "    -> Używane w: kroku 3 (deploy modelu LLM)"
echo ""
echo "  OLLAMA_REPO_DESCRIPTION=$OLLAMA_REPO_DESCRIPTION"
echo "    -> Opis repozytorium na Artifact Registry."
echo "    -> Używane w: kroku 3 (deploy modelu LLM)"
echo ""
echo "  PUBSUB_PUBLISH_TOPIC=$PUBSUB_PUBLISH_TOPIC"
echo "    -> Pełna ścieżka tematu Pub/Sub w projekcie organizatora."
echo "    -> Używane w: kroku 2 (żądanie dostępu do bucketu z modelami)"
echo ""
echo "======================================================"
echo " UWAGA: Te zmienne obowiązują tylko w bieżącym terminalu."
echo " W każdym NOWYM terminalu uruchom ponownie: source setup_env.sh"
echo "======================================================"
echo ""
