#!/bin/bash

# Ustawienie zmiennych środowiskowych
export PROJECT_ID=$(gcloud config get-value project)
export REGION="europe-west1"
export EMBEDDING_SERVICE="embedding-gemma"
export LLM_SERVICE="bielik"
export BIGQUERY_DATASET="rag_dataset"
export BIGQUERY_TABLE="hotel_rules"

echo ""
echo "======================================================"
echo " UWAGA: Materiał warsztatowy - tylko do celów edukacyjnych!"
echo " Nie stosować w środowiskach produkcyjnych."
echo "======================================================"
echo ""
echo "======================================================"
echo " Zmienne środowiskowe wczytane pomyślnie!"
echo "======================================================"
echo ""
echo "  PROJECT_ID=$PROJECT_ID"
echo "    -> ID Twojego projektu Google Cloud."
echo "    -> Używane w: krokach 2, 3, 4, 5 (wszystkie usługi GCP)"
echo ""
echo "  REGION=$REGION"
echo "    -> Region Google Cloud, w którym uruchamiane są usługi."
echo "    -> Używane w: krokach 3, 5 (Cloud Run)"
echo ""
echo "  LLM_SERVICE=$LLM_SERVICE"
echo "    -> Nazwa usługi Cloud Run z modelem językowym Bielik."
echo "    -> Używane w: kroku 3 (deploy modelu LLM)"
echo ""
echo "  EMBEDDING_SERVICE=$EMBEDDING_SERVICE"
echo "    -> Nazwa usługi Cloud Run z modelem embeddingowym EmbeddingGemma."
echo "    -> Używane w: kroku 3 (deploy modelu embeddingowego)"
echo ""
echo "  BIGQUERY_DATASET=$BIGQUERY_DATASET"
echo "    -> Nazwa zbioru danych (dataset) w BigQuery."
echo "    -> Używane w: kroku 4 (inicjalizacja bazy) i kroku 6 (wyszukiwanie RAG)"
echo ""
echo "  BIGQUERY_TABLE=$BIGQUERY_TABLE"
echo "    -> Nazwa tabeli w BigQuery przechowującej dokumenty i wektory."
echo "    -> Używane w: kroku 4 (inicjalizacja bazy) i kroku 6 (wyszukiwanie RAG)"
echo ""
echo "======================================================"
echo " UWAGA: Te zmienne obowiązują tylko w bieżącym terminalu."
echo " W każdym NOWYM terminalu uruchom ponownie: source setup_env.sh"
echo "======================================================"
echo ""
